name: gyawun
description: "A powerful Flutter-based offline music app."
publish_to: 'none'
version: 2.0.13+38

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  fluent_ui: ^4.9.2

  # Core Utilities
  intl: ^0.20.2
  http: ^1.2.2
  provider: ^6.1.2
  get_it: ^8.0.3
  path: ^1.9.0
  path_provider: ^2.1.3
  file_picker: ^10.1.9
  pub_semver: ^2.1.4
  permission_handler: ^11.4.0
  device_info_plus: ^11.4.0

  # Audio & Playback
  just_audio: ^0.10.3
  just_audio_background: ^0.0.1-beta.14
  just_audio_media_kit: ^2.0.6
  media_kit_libs_windows_audio: any
  media_kit_libs_linux: any
  media_kit_native_event_loop: any
  audio_video_progress_bar: ^2.0.3
  flutter_lyric: ^2.0.4+6
  audiotags: ^1.4.3

  # UI Widgets
  expandable_page_view: ^1.0.17
  flutter_typeahead: ^5.2.0
  expandable_text: ^2.3.0
  share_plus: ^11.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_swipe_action_cell: ^3.1.3
  sliding_up_panel: ^2.0.0+1
  text_scroll: ^0.2.0
  duration_picker: ^1.2.0
  flutter_acrylic: ^1.1.4
  window_manager: ^0.4.3
  flutter_expandable_fab: ^2.1.0
  easy_folder_picker: ^1.3.3
  flutter_colorpicker: ^1.1.0

  # Networking / Platform
  url_launcher: ^6.3.0
  country_picker: ^2.0.26
  cached_network_image: ^3.3.1
  youtube_explode_dart:
    git:
      url: https://github.com/sheikhhaziq/youtube_explode_dart.git
  receive_sharing_intent:
    git:
      url: https://github.com/sheikhhaziq/receive_sharing_intent.git

  # Color & Design
  dynamic_color: ^1.7.0
  palette_generator: ^0.3.3+4 # ❗ discontinued, no longer maintained

  # Markdown
  flutter_markdown: ^0.7.3 # ❗ discontinued, consider `markdown_widget`

  # Toast
  fl_toast: ^3.2.0 # ❗ discontinued

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.3.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
