name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux-snap:
    name: Build Snap Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version: "3.29.3"

      - name: Enable Linux platform (if not already enabled)
        run: flutter create --platforms=linux .

      - name: Patch intl version (Fix pubspec conflict)
        run: |
          sed -i 's/intl: \^0.19.0/intl: ^0.20.2/' pubspec.yaml

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev libmpv-dev libfuse2 ninja-build cmake clang

      - name: Build Flutter Linux App
        run: flutter build linux

      - name: Build Snap with Snapcraft
        uses: snapcore/action-build@v1
        id: snapcraft
        env:
          # Prevent Flutter running as root warning
          FLUTTER_ROOT: ${{ github.workspace }}/flutter

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gyawunmusic-snap
          path: ${{ steps.snapcraft.outputs.snap }}
