name: Code quality check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  text:
    name: Check the source code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17.0.10

      - name: Install packages
        run: flutter pub get

      - name: Linter
        run: flutter analyze || true

      - name: build check
        run: flutter build apk

      - uses: actions/upload-artifact@v4
  with:
    name: release-apk
    path: build/app/outputs/flutter-apk/app-release.apk
